# TCL File Generated by Component Editor 18.1
# Sun Aug 30 20:41:57 CEST 2020
# DO NOT MODIFY


# 
# DisplayHDMIText "DisplayHDMIText" v1.0
# Piotr Rzeszut Systemy embedded w FPGA 2020.08.30.20:41:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DisplayHDMIText
# 
set_module_property DESCRIPTION ""
set_module_property NAME DisplayHDMIText
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Display
set_module_property AUTHOR "Piotr Rzeszut Systemy embedded w FPGA"
set_module_property DISPLAY_NAME DisplayHDMIText
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DisplayHDMI
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DisplayHDMI.vhd VHDL PATH ../DisplayHDMI/DisplayHDMI.vhd TOP_LEVEL_FILE
add_fileset_file HDMIDriver.vhd VHDL PATH ../DisplayHDMI/HDMIDriver.vhd
add_fileset_file LVDS.v VERILOG PATH ../DisplayHDMI/LVDS.v
add_fileset_file TMDS.vhd VHDL PATH ../DisplayHDMI/TMDS.vhd
add_fileset_file charRAMHDMI.vhd VHDL PATH ../DisplayHDMI/charRAMHDMI.vhd
add_fileset_file dividerHDMI.vhd VHDL PATH ../DisplayHDMI/dividerHDMI.vhd
add_fileset_file fontROMHDMI.vhd VHDL PATH ../DisplayHDMI/fontROMHDMI.vhd
add_fileset_file multiplier106HDMI.vhd VHDL PATH ../DisplayHDMI/multiplier106HDMI.vhd
add_fileset_file multiplier6HDMI.vhd VHDL PATH ../DisplayHDMI/multiplier6HDMI.vhd

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL DisplayHDMI
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file DisplayHDMI.vhd VHDL PATH ../DisplayHDMI/DisplayHDMI.vhd
add_fileset_file HDMIDriver.vhd VHDL PATH ../DisplayHDMI/HDMIDriver.vhd
add_fileset_file LVDS.v VERILOG PATH ../DisplayHDMI/LVDS.v
add_fileset_file TMDS.vhd VHDL PATH ../DisplayHDMI/TMDS.vhd
add_fileset_file charRAMHDMI.vhd VHDL PATH ../DisplayHDMI/charRAMHDMI.vhd
add_fileset_file dividerHDMI.vhd VHDL PATH ../DisplayHDMI/dividerHDMI.vhd
add_fileset_file fontROMHDMI.vhd VHDL PATH ../DisplayHDMI/fontROMHDMI.vhd
add_fileset_file multiplier106HDMI.vhd VHDL PATH ../DisplayHDMI/multiplier106HDMI.vhd
add_fileset_file multiplier6HDMI.vhd VHDL PATH ../DisplayHDMI/multiplier6HDMI.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL DisplayHDMI
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file DisplayHDMI.vhd VHDL PATH ../DisplayHDMI/DisplayHDMI.vhd
add_fileset_file HDMIDriver.vhd VHDL PATH ../DisplayHDMI/HDMIDriver.vhd
add_fileset_file LVDS.v VERILOG PATH ../DisplayHDMI/LVDS.v
add_fileset_file TMDS.vhd VHDL PATH ../DisplayHDMI/TMDS.vhd
add_fileset_file charRAMHDMI.vhd VHDL PATH ../DisplayHDMI/charRAMHDMI.vhd
add_fileset_file dividerHDMI.vhd VHDL PATH ../DisplayHDMI/dividerHDMI.vhd
add_fileset_file fontROMHDMI.vhd VHDL PATH ../DisplayHDMI/fontROMHDMI.vhd
add_fileset_file multiplier106HDMI.vhd VHDL PATH ../DisplayHDMI/multiplier106HDMI.vhd
add_fileset_file multiplier6HDMI.vhd VHDL PATH ../DisplayHDMI/multiplier6HDMI.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 11
add_interface_port avalon_slave_0 byteenable byteenable Input 4
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point HDMI
# 
add_interface HDMI conduit end
set_interface_property HDMI associatedClock clock
set_interface_property HDMI associatedReset ""
set_interface_property HDMI ENABLED true
set_interface_property HDMI EXPORT_OF ""
set_interface_property HDMI PORT_NAME_MAP ""
set_interface_property HDMI CMSIS_SVD_VARIABLES ""
set_interface_property HDMI SVD_ADDRESS_GROUP ""

add_interface_port HDMI HDMI_TMDS hdmi_tmds Output 3
add_interface_port HDMI HDMI_TMDS_CLK hdmi_tmds_clk Output 1


# 
# connection point clock25
# 
add_interface clock25 clock end
set_interface_property clock25 clockRate 25000000
set_interface_property clock25 ENABLED true
set_interface_property clock25 EXPORT_OF ""
set_interface_property clock25 PORT_NAME_MAP ""
set_interface_property clock25 CMSIS_SVD_VARIABLES ""
set_interface_property clock25 SVD_ADDRESS_GROUP ""

add_interface_port clock25 HDMI_CLK25 clk Input 1


# 
# connection point clock250
# 
add_interface clock250 clock end
set_interface_property clock250 clockRate 250000000
set_interface_property clock250 ENABLED true
set_interface_property clock250 EXPORT_OF ""
set_interface_property clock250 PORT_NAME_MAP ""
set_interface_property clock250 CMSIS_SVD_VARIABLES ""
set_interface_property clock250 SVD_ADDRESS_GROUP ""

add_interface_port clock250 HDMI_CLK250 clk Input 1

